### ISSUE TITLE
onChange event isn't firing

### ISSUE THREAD

**Issue by rickmurt** [uploadcare/uploadcare-widget-react-demo#10]
Hi there,

Cloned the repo, `npm install`, `npm start` without changing any code. Noticed that when I uploaded a file, the onUploadComplete callback fired, but the onChange callback never did.

This demo repo uses 3.3, I tried with 3.6 and noticed the same result.

**Comment by Zmoki** [comment]
@rickmurt hi! Thank you for the report! I fixed it, please, pull and check it
