### ISSUE TITLE
How to track changes on multiple widgets on the same page?

### ISSUE THREAD

**Issue by VSVS** [uploadcare/uploadcare-widget-react-demo#12]
Hey All,

The widget.onUploadComplete returns a cdn url but i cant seem to assign this url by name in my parent state. I have 5 widgets in my component. One of my attempts were to wrap my Uploader component in a div with an onChange callback function and use event.target.name to setState by name and assign that cdnUrl. I referenced this [issue](https://github.com/uploadcare/uploadcare-widget-react-demo/issues/2) which makes sense but i cant seem to wrap my head around this. I want to avoid using something like redux for something simple like this. What's the easiest way to assign the input's name to the cdnUrl when it's updated or changed? Thanks!

**Comment by Zmoki** [comment]
@VSVS hi!

I created an example app with state and Uploader, https://codesandbox.io/s/jjmr3zvkn9, I use the `updateUUID` method to bind names of inputs with UUIDs. It‘s the right way for you?

**Comment by VSVS** [comment]
Hey @Zmoki 

Yes! Elegant and simple solution. Thanks for the help and awesome platform!
